---
# File: .github/workflows/guacamole-host.yml
name: Guacamole-Host

on: [workflow_dispatch]

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    - name: Clone Guacamole Docker
      run: |
        git clone https://github.com/boschkundendienst/guacamole-docker-compose.git
        cd guacamole-docker-compose
        sudo docker-compose up -d

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requirements
      run: pip install -r firebase/requirements.txt

    - name: Wait for RDP Address from Firebase and Loop Output
      shell: bash
      run: |
        while true; do
          RDP_ADDR=$(python firebase/fetch_data.py https://your-project.firebaseio.com rdpAddress)
          if [[ "$RDP_ADDR" == serveo.net:* ]]; then
            echo "Guacamole URL: http://localhost:8080/guacamole/#/client/c/$RDP_ADDR"
            break
          fi
          echo "Waiting for RDP address..."
          sleep 10
        done

        # Keep container alive until signal
        while true; do
          GUAC_SHUTDOWN=$(python firebase/fetch_data.py https://your-project.firebaseio.com guacShutdown)
          if [[ "$GUAC_SHUTDOWN" == true ]]; then
            echo "Shutting down Guacamole host..."
            cd guacamole-docker-compose
            sudo docker-compose down
            break
          fi
          sleep 30
        done

