name: Guacamole-Host

on: [workflow_dispatch]

jobs:
  guac:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Start Guacamole Containers
      run: |
        docker network create guacnet || true
        docker run -d --name guacd --net guacnet guacamole/guacd
        docker run -d --name guacamole --net guacnet -p 8080:8080 \
          -e GUACD_HOSTNAME=guacd \
          -e MYSQL_HOSTNAME= \
          guacamole/guacamole

    - name: Wait for RDP Address in Firebase
      shell: bash
      run: |
        echo "Waiting for RDP address in Firebase..."
        while true; do
          RDP_ADDR=$(python firebase/fetch_data.py rdpAddress)
          if [ "$RDP_ADDR" != "null" ] && [ -n "$RDP_ADDR" ]; then
            echo "RDP Address found: $RDP_ADDR"
            break
          fi
          sleep 5
        done

    - name: Output Guacamole URL
      run: |
        echo "You can access RDP via Guacamole at: http://localhost:8080/#/client/${RDP_ADDR}"
        # In real deploy, replace localhost with public IP/domain.

    - name: Monitor Shutdown Flag and Cleanup
      shell: bash
      run: |
        echo "Monitoring shutdown flag..."
        while true; do
          FLAG=$(python firebase/fetch_data.py guacShutdown)
          echo "Shutdown flag: $FLAG"
          if [ "$FLAG" == "true" ]; then
            echo "Shutdown flag detected. Stopping Guacamole..."
            docker stop guacamole guacd
            docker rm guacamole guacd
            break
          fi
          sleep 20
        done
