name: Windows-RDP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Start Serveo Tunnel
      run: |
        nohup ssh -o StrictHostKeyChecking=no -R 0:localhost:3389 serveo.net -N > serveo.log 2>&1 &
        # wait until port allocated
        while ((Get-Content serveo.log) -notmatch 'Allocated port') { Start-Sleep -Seconds 1 }
      shell: powershell

    - name: Upload RDP Address to Firebase
      env:
        FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      working-directory: windows
      run: python firebase/upload_data.py rdp_address.txt

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      working-directory: windows
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 60 }
      shell: powershell

    - name: Trigger Guacamole Shutdown
      run: |
        curl -X POST https://your-guacamole-shutdown-endpoint

