---
# File: .github/workflows/windows-rdp.yml
name: Windows-RDP

on: [workflow_dispatch]

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start Serveo Tunnel
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -R 0:localhost:3389 serveo.net -N 2>&1 | tee serveo.log &
        echo $! > ssh_pid.txt
        sleep 10

        while ! grep -q 'Forwarding TCP port' serveo.log; do sleep 1; done
        PUBLIC_ADDR=$(grep 'Forwarding TCP port' serveo.log | tail -1 | sed -E 's/.*Forwarding TCP port ([0-9]+).*/serveo.net:\1/')
        echo "RDP Address: $PUBLIC_ADDR"
        echo $PUBLIC_ADDR > rdp_address.txt

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requirements
      run: pip install -r firebase/requirements.txt

    - name: Upload RDP Address to Firebase
      run: |
        python firebase/upload_data.py https://your-project.firebaseio.com rdpAddress "$(<rdp_address.txt)"

    - name: Trigger Guacamole Shutdown (on exit)
      if: always()
      run: |
        python firebase/upload_data.py https://your-project.firebaseio.com guacShutdown true

    - name: Keep Alive
      shell: bash
      run: |
        echo "Keeping the workflow alive for RDP session..."
        while true; do sleep 60; done
